export const favouritesRoomsSelector = (state) => state.favouritesRooms;
export const favouritesServicesSelector = (state) => state.favouritesServices;
export const avatarSelector = (state) => state.avatar;
export const bookmarkRoomsSelector = (state) => state.bookmarkRooms;
// export const roomTypesSelector = (state) => state.roomTypes;
// export const servicesSelector = (state) => state.services;
export const checkinDateSelector = (state) => state.checkinDate;
export const checkoutDateSelector = (state) => state.checkoutDate;
export const progressStepSelector = (state) => state.progressStep;
export const totalAmountSelector = (state) => state.totalAmount;